baseurl = "https://swarodaya.com"
publishdir = "public"
languageCode = "en-us"
title = "Swarodaya - Maximize Your Potential"
canonifyurls = false
googleAnalytics = "UA-25128293-7"

[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Swarodaya"
    description = "Maximize Your Potential"
    keywords = "Swaryog,Swaryoga,Swarayog,Swarayoga,meditation,breathing,breathe,breath,patanjali,yogsutra"

    # The path must be relative to the static folder
    favicon = "favicon.png"


    # Navigation
    [params.navigation]
        brand = "Home"

        [params.navigation.links]
            intro     = "Intro"
            benefits  = "Benefits"
            enrol     = "Residential Course"
            online    = "Online Course"
            services  = "Services"
            acharya   = "Alumni"
            contact   = "Contact"
            recentposts   = "Recent"

    [[menu.main]]
        name = "Videos"
        identifier = "videos"
        url = "/videos/"
        weight = 1

    [[menu.main]]
        name = "Blog"
        identifier = "blog"
        url = "/blog/"
        weight = 3

    # Hero section
    [params.hero]
        # To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
        slogan     = "Swarodaya"
        subtitle   = "Maximize Your Potential"

		# Intro section
    [params.intro]
        headline = "Introduction"
        bg = "bg-dark"
        text = "Swarodaya, a vision of Acharya Seema Karecha, is aimed at helping individuals transform their lives through ancient vedic knowledge. Hailing from a cultural background of artistic lineage, she holds degrees in Philosophy, Psychology, and English literature. As an explorer of timeless wisdom, she paved her spiritual journey with the knowledge of Swar Yog, Yog Sutras of Patanjali, Vastu Shastra, and Astrology under the guidance of accomplished gurus. She conducts training programs and provides services, where she teaches the essence of these mystical sciences that can help a modern person find happiness and prosperity."

    # Videos section
    [params.videos]
        headline = "Videos"

        [[params.videos.list]]
		title = "Ms Gaitry Kaul"
		video = "https://www.youtube.com/embed/iV0m_HjUNlY?autoplay=0"

        [[params.videos.list]]
            title = "Dr Jai Madaan"
            video = "https://www.youtube.com/embed/p23NctTfzK4?autoplay=0"

        [[params.videos.list]]
            title = "Mr Aman Gupta"
            video = "https://www.youtube.com/embed/TLkKORg6uhA?autoplay=0"

        [[params.videos.list]]
            title = "Mr Abhishek Bansal"
            video = "https://www.youtube.com/embed/1-gF_RpYkY4?autoplay=0"

        [[params.videos.list]]
		title = "Ms Gaitry Kaul"
		video = "https://www.youtube.com/embed/KnAQQXmryGA?autoplay=0"

        [[params.videos.list]]
		title = "Mr Tushal Deep Singh"
		video = "https://www.youtube.com/embed/IQAO5d2V-VQ?autoplay=0"

        [[params.videos.list]]
            title = "The Element Of Air"
            video = "https://www.youtube.com/embed/jdGNHGONGBc?autoplay=0"

        [[params.videos.list]]
            title = "Swaryog"
            video = "https://www.youtube.com/embed/U98nDu6tjTs?autoplay=0"

        [[params.videos.list]]
            title = "Introduction to Swaryog"
            video = "https://www.youtube.com/embed/6rN7s8BE9rI?autoplay=0"

        [[params.videos.list]]
            title = "Purpose of Life"
            video = "https://www.youtube.com/embed/LAmlgk0KI8E?autoplay=0"

        [[params.videos.list]]
            title = "Story of Patanjali"
            video = "https://www.youtube.com/embed/lcIVSxLiHAI?autoplay=0"

        [[params.videos.list]]
            title = "Predictions with Swar"
            video = "https://www.youtube.com/embed/r3SV4R_iBnA?autoplay=0"

        [[params.videos.list]]
            title = "Tatwas and Mahabharat"
            video = "https://www.youtube.com/embed/DWZXFemaeZ8?autoplay=0"

        [[params.videos.list]]
            title = "Make Swar Your Strength"
            video = "https://www.youtube.com/embed/h3F_2gk-4q4?autoplay=0"

    # Benefits section
    [params.benefits]
        headline = "Benefits of Learning"
        bg  = "bg-light"
	text = "These are the tools, when understood and executed meaningfully, makes living a joy."

        [[params.benefits.list.row1]]
            title = "Swar Yog"
            text = "<p>Swaryog is an ancient indian science of breath awareness that has been practiced by yogis, spiritual masters, and seers of India, since thousands of years, to create a life of prosperity and abundance.<br/><br/> Swar is breath and yog is to unite. Swaryog is a science where we unite with our breath to gain an understanding of the self and our universe. Swar or breath can be understood in terms of Nadis and Tatwas. When the breath flows from the left nostril, it is referred as the Chandra Swar and is associated with the Ida nadi of our body. When the breath flows from the right nostril, it is referred as the Surya Swar and is associated with the Pingala Nadi of our body.  When the breath flows from the both the nostrils, at once, it is referred as the Shunya Swar and is connected with the Sushumna nadi of our body. The breath, depending on the flow is associated with the different nadis, which in turn, has different effects on our mind and body.<br/><br/>To add to the effect of these nadis, is the dimension of 'tatwas' or elements. The place in the nostril through which the breath flows, is referred as the 'element' or 'tatwa' of the breath. There are five different elements (Space, Air, Fire, Earth, and Water) that can flow in a nostril at a given time.<br/><br/>This combined play of Nadis and Tatwas is the science of Swaryog. It not only helps you raise your awareness and, connect deeply within, and feel grounded and rooted, but also is of immense help in decision making, event planning, foreseeing events, creating abundance and prosperity.<br/><br/>During the session, students learn to recognize the Nadis, the Tatwas and understand their properties and usage  for their personal and professional use." 

        [[params.benefits.list.row1]]
            title = "Patanjali Yog Sutra"
            text = "<p>The Yog Sutras were codified by Sage Patanjali about 5000 years ago in Sanskrit. The sutras, 196 in number and divided into 4 Padas or chapters, deals in depth with subjects like Samadhi and its forms, Sadhana and its various methods, Siddhis - their attainments and results, and Kaivalya - the science and art of being in Flow. The popular Ashtang Yog form the core of these Sutras. The aim of the Yog Sutras is to help an individual attain immense clarity about the self, life, people and situations, giving a framework and structure to daily living. It is a guide to raising potential to the maximum and living life to the fullest, maintaining calm and composure even in stressful situations. The Yog Sutras helps us identify, and then plug, our energy leakages on mental and physical level, helping us evolve, be efficient, better organized and gain inner strength.<br/><br/>During the course, Acharya Seema renders her understanding of these complex sutras in simple english and help the student grasp their crux and help make use of the understanding gained to simplify and enhance life."


        [[params.benefits.list.row2]]
            title = "Meditation"
            text = "<p>Many of us meditate - or have at least tried to meditate - but may not have found the results satisfactory. Many a times, when we sit to meditate, we end up closing our eyes and lose ourselves in thoughts, and fail to get the desired benefits. There are special techniques that must be followed to experience deep meditative states. At Swarodaya, students are beautifully guided through thoughtfully designed techniques to bring in a state where they are actually able to immerse themselves in the state of deep meditation. The specially designed meditative techniques help one expand the threshold of awareness leading one towards more insightful and enlightened living."

        [[params.benefits.list.row2]]
            title = "Yogic Tools for Abundance"
            text = "<p>The Yogic tools for abundance - Mantra, Yantra, and Tantra - help invite prosperity and abundance at all levels. It reduces the day-to-day struggles, helping life flow smoothly.<ul> <li>Mantra - In the Mantra sessions, students are guided through the basic understanding of Mantras and their usage in practical life. Guidelines are given on how to use Mantras in various areas of life, for e.g. how to make the day successful, eliminate negativity from the environment and food, reduce stress and create abundance. A special vedic ritual called Agni Pooja is taught to the students - where they learn to use Mantras with Agni to create a harmonious life.  <li>Yantra - In the Yantra session, students are blessed with Sri Yantra, are guided through its mysterious formation. They learn the ancient sacred process of it’s pooja and are blessed into the sadhana. Sri Yantra is said to be the King of Yantras, and its sadhana of which is said to be immensely beneficial to create abundance at all levels.  <li>Tantra - In the Tantra session, the students undergo an ancient meditation. This ancient and scared meditation, help the students emerge emotionally and spiritually uplifted after the process."

    # Benefits videos section. This list of videos go on the front page
    [params.benefits.videos]
        headline = "Videos"

        [[params.benefits.videos.list]]
            title = "The Element Of Air"
            video = "https://www.youtube.com/embed/jdGNHGONGBc?autoplay=0"

        [[params.benefits.videos.list]]
		title = "Ms Gaitry Kaul"
		video = "https://www.youtube.com/embed/iV0m_HjUNlY?autoplay=0"

        [[params.benefits.videos.list]]
		title = "Mr Tushal Deep Singh"
		video = "https://www.youtube.com/embed/IQAO5d2V-VQ?autoplay=0"

        [[params.benefits.videos.list]]
            title = "Dr Jai Madaan"
            video = "https://www.youtube.com/embed/p23NctTfzK4?autoplay=0"

    # Aside section
    [params.course]
        headline = "Residential Course"
        bg = "bg-dark"
        text = ""
	listheadline = "Registrations will open soon"
	#listheadline1 = "Course Schedule: 12, 13, 14, 15 January 2019"
	#listheadline2 = "Venue: The Lalit, Udaipur"

        [[params.course.list]]
            title = "SwarYog"
            text = "<ul> <li>Nadis</li> <li>Tattvas</li> <li>Practicals</li> </ul>"

        [[params.course.list]]
            title = "Yog Sutras"
            text = "<ul> <li>Samadhi Pada</li> <li>Sadhana Pada</li> <li>Vibhuti Pada</li> <li>Kaivalya Pada</li> </ul>"

        [[params.course.list]]
            title = "Meditations"
            text = "<ul> <li>Mindfulness Meditation</li> <li>Elemental Meditation</li> <li>Sushumna Meditation</li> </ul>"

        [[params.course.list]]
            title = "Abundance"
            text = "<ul> <li>Mantra</li> <li>Yantra (Sri Yantra)</li> <li>Tantra</li> </ul>"

    # Aside section
    [params.online]
        headline = "Online Course"
        bg = "bg-light"
        text = "The Swarodaya Online Learning Programme is designed mainly for the overseas learner, and is conducted on one-to-one basis through the medium of Skype/Facetime video calling.<p> The entire training programme spans over 12 sessions, with one session conducted every week. The duration of each session is two hours, and the training is covered over a period of 3 months."
	energy = "Energy Exchange: 1,08,000 INR"
	content = "Course Content: Same as Residential Course"

    # Services section
    [params.services]
        headline = "Services"
        bg  = "bg-dark"
	text = ""

        [[params.services.list]]
            icon = "fa-home"
            title = "Vastu Shastra"
            text = "Vastu Shastra is an ancient Indian science that is based upon the laws of nature and its effects on human dwellings. It formlates the rules for living spaces that would ensure harmony, prosperity, and health for its residents. These laws are based on the five elements of nature — Water, Air, Fire, Earth, and Space — and their effects on human life.<br/><br/> We at Swarodaya, provide simple and effective solutions  to make your living space vastu compliant, and we do this without recommending structural demolitions. We study the floor plan and interior design of your residence, and then align it with your horoscope based on your planetary strengths, to give customized recommendations for non-destructive changes.  These changes help you realize your goals and aspirations, and also help you resolve your life challenges and problems.<br/><br/> We help you to: <ul> <li>Gain new career opportunities and growth in your field of work.</li> <li>Improve your finances</li> <li>Strengthening of relations within family, friends, and colleagues.</li> <li>Help children learn better and perform at the best of their abilities.</li> <li>Reduce mental stress, enhance clarity of thought and increase the peace of mind.</li> </ul>"

        [[params.services.list]]
            icon = "fa-star"
            title = "Astrology"
            text = "Jyotish - Astrology - is an ancient traditional Hindu system of astrology, and is one of the most time-tested and oldest systems in the world. The Sanskrit word 'Jyotish' (ja-yo-teesh) means 'light of God.' The Light that guides the inner self, reducing uncertainty, allowing us to plan our future.<br/><br/> At Swarodaya, we provide you with effective astrological solutions, which include use of gemstones and mantras to help you overcome obstacles in life with ease, and achieve your goals.<br/><br/> We analyze your birth-chart to help you understand:<ul> <li>Your inner self, your strengths and your weakness, your natural skills and abilities.</li> <li>Understand the cycles of your life: your favorable and unfavorable years.</li> <li>Provide astrological recommendations to overcome the difficult periods of life through gemstones and other solutions.</li> <li>Provide guidance in matters of education, on the choice of careers, profession and other important aspects of life.</li> <li>Help determine when to begin a project, a new enterprise or relocation.</li> </ul>"

    # Acharya section
    [params.acharya]
        headline = "Residential Course Alumni"
        bg = "bg-light"
        title = "Batch of Sept, 2016<br/>Goa"
        img = "acharya.jpg"
        batch_title1 = "Batch of Sept, 2016<br/>Goa"
        batch_img1 = "201709goa.jpg"
        batch_title2 = "Batch of Feb, 2017<br/>Udaipur"
        batch_img2 = "201702udaipur.jpg"
        batch_title3 = "Batch of Feb, 2018<br/>Udaipur"
        batch_img3 = "201802udaipur.jpg"
        batch_title4 = "Batch of Sep, 2018<br/>Udaipur"
        batch_img4 = "201809udaipur.jpg"
        #text = "xyz"

		# Recent posts section
    [params.recentposts]
        headline = "Blog"
        bg = "bg-dark"

    # Contact section
    [params.contact]
        headline = "Get In Touch!"
        bg = "bg-light"
        description = ""

        [[params.contact.list]]
            icon = "fa-envelope"
            text = "[info@swarodaya.com](mailto:info@swarodaya.com?subject=General Inquiry)"

        [[params.contact.list]]
            icon = "fa-facebook"
            text = "[https://www.facebook.com/swarodaya/](https://www.facebook.com/swarodaya/)"

        [[params.contact.list]]
            icon = "fa-phone"
            text = "+91-9825-600347<br/>+91-9989-670951"

